import type { PlantSeed, Customer, Seller } from "./types"

export const PLANT_SEEDS: PlantSeed[] = [
  // FERNS
  {
    id: "asparagus-fern",
    name: "Asparagus Fern",
    image: "/plants/001-asparagus fern.svg",
    family: "Fern",
    genus: "Asparagus",
    species: "setaceus",
    tags: ["fern", "feathery", "trailing", "delicate", "beginner"],
    baseTraits: { rarity: 25, demand: 55, careDifficulty: 35, propagationSpeed: 60 },
    baseFMV: 15,
  },
  {
    id: "birds-nest-fern",
    name: "Bird's Nest Fern",
    image: "/plants/016-birds nest fern.svg",
    family: "Fern",
    genus: "Asplenium",
    species: "nidus",
    tags: ["fern", "tropical", "low-light", "beginner"],
    baseTraits: { rarity: 30, demand: 60, careDifficulty: 30, propagationSpeed: 40 },
    baseFMV: 22,
  },
  {
    id: "staghorn-fern",
    name: "Staghorn Fern",
    image: "/plants/028-staghorn fern.svg",
    family: "Fern",
    genus: "Platycerium",
    species: "bifurcatum",
    tags: ["fern", "epiphytic", "unusual", "collector"],
    baseTraits: { rarity: 50, demand: 70, careDifficulty: 55, propagationSpeed: 35 },
    baseFMV: 45,
  },

  // AROIDS
  {
    id: "chinese-evergreen",
    name: "Chinese Evergreen",
    image: "/plants/002-chinese evergreen.svg",
    family: "Aroid",
    genus: "Aglaonema",
    species: "commutatum",
    tags: ["aroid", "low-light", "beginner", "patterned", "easy-care"],
    baseTraits: { rarity: 20, demand: 65, careDifficulty: 15, propagationSpeed: 50 },
    baseFMV: 18,
  },
  {
    id: "monstera",
    name: "Monstera",
    image: "/plants/003-monstera.svg",
    family: "Aroid",
    genus: "Monstera",
    species: "deliciosa",
    tags: ["aroid", "tropical", "fenestrated", "statement", "popular", "trendy"],
    baseTraits: { rarity: 30, demand: 90, careDifficulty: 25, propagationSpeed: 45 },
    baseFMV: 35,
  },
  {
    id: "monstera-adansonii",
    name: "Monstera Adansonii",
    image: "/plants/046-monstera.svg",
    family: "Aroid",
    genus: "Monstera",
    species: "adansonii",
    tags: ["aroid", "tropical", "fenestrated", "trailing", "collector", "trendy"],
    baseTraits: { rarity: 45, demand: 85, careDifficulty: 30, propagationSpeed: 50 },
    baseFMV: 42,
  },
  {
    id: "pothos",
    name: "Pothos",
    image: "/plants/006-pothos.svg",
    family: "Aroid",
    genus: "Epipremnum",
    species: "aureum",
    tags: ["aroid", "trailing", "beginner", "easy-care", "versatile", "popular"],
    baseTraits: { rarity: 10, demand: 70, careDifficulty: 10, propagationSpeed: 85 },
    baseFMV: 8,
  },
  {
    id: "alocasia",
    name: "Alocasia",
    image: "/plants/010-alocasia.svg",
    family: "Aroid",
    genus: "Alocasia",
    species: "amazonica",
    tags: ["aroid", "tropical", "dramatic", "collector", "bold"],
    baseTraits: { rarity: 55, demand: 75, careDifficulty: 60, propagationSpeed: 30 },
    baseFMV: 45,
  },
  {
    id: "peace-lily",
    name: "Peace Lily",
    image: "/plants/017-peace lily.svg",
    family: "Aroid",
    genus: "Spathiphyllum",
    species: "wallisii",
    tags: ["aroid", "flowering", "low-light", "beginner", "air-purifying"],
    baseTraits: { rarity: 15, demand: 65, careDifficulty: 20, propagationSpeed: 50 },
    baseFMV: 20,
  },
  {
    id: "anthurium",
    name: "Anthurium",
    image: "/plants/021-anthurium.svg",
    family: "Aroid",
    genus: "Anthurium",
    species: "andraeanum",
    tags: ["aroid", "flowering", "tropical", "colorful", "statement"],
    baseTraits: { rarity: 35, demand: 70, careDifficulty: 40, propagationSpeed: 40 },
    baseFMV: 28,
  },
  {
    id: "philodendron",
    name: "Philodendron",
    image: "/plants/031-philodendron.svg",
    family: "Aroid",
    genus: "Philodendron",
    species: "cordatum",
    tags: ["aroid", "trailing", "beginner", "easy-care", "versatile"],
    baseTraits: { rarity: 20, demand: 75, careDifficulty: 15, propagationSpeed: 70 },
    baseFMV: 18,
  },
  {
    id: "rubber-plant",
    name: "Rubber Plant",
    image: "/plants/024-rubber plant.svg",
    family: "Aroid",
    genus: "Ficus",
    species: "elastica",
    tags: ["aroid", "statement", "large", "trendy", "bold"],
    baseTraits: { rarity: 25, demand: 80, careDifficulty: 30, propagationSpeed: 35 },
    baseFMV: 30,
  },

  // PRAYER PLANTS / MARANTACEAE
  {
    id: "prayer-plant",
    name: "Prayer Plant",
    image: "/plants/004-maranta prayer plant.svg",
    family: "Marantaceae",
    genus: "Maranta",
    species: "leuconeura",
    tags: ["prayer-plant", "patterned", "colorful", "movement"],
    baseTraits: { rarity: 35, demand: 70, careDifficulty: 45, propagationSpeed: 55 },
    baseFMV: 22,
  },
  {
    id: "calathea",
    name: "Calathea",
    image: "/plants/022-calathea.svg",
    family: "Marantaceae",
    genus: "Calathea",
    species: "ornata",
    tags: ["prayer-plant", "patterned", "colorful", "collector", "humidity-loving"],
    baseTraits: { rarity: 40, demand: 75, careDifficulty: 55, propagationSpeed: 40 },
    baseFMV: 35,
  },

  // PALMS
  {
    id: "parlor-palm",
    name: "Parlor Palm",
    image: "/plants/005-parlor palm.svg",
    family: "Palm",
    genus: "Chamaedorea",
    species: "elegans",
    tags: ["palm", "low-light", "elegant", "classic", "beginner"],
    baseTraits: { rarity: 15, demand: 60, careDifficulty: 20, propagationSpeed: 35 },
    baseFMV: 20,
  },
  {
    id: "ponytail-palm",
    name: "Ponytail Palm",
    image: "/plants/029-ponytail palm.svg",
    family: "Asparagaceae",
    genus: "Beaucarnea",
    species: "recurvata",
    tags: ["palm", "succulent", "beginner", "easy-care", "unusual"],
    baseTraits: { rarity: 25, demand: 65, careDifficulty: 15, propagationSpeed: 30 },
    baseFMV: 25,
  },
  {
    id: "bamboo",
    name: "Lucky Bamboo",
    image: "/plants/043-bamboo.svg",
    family: "Asparagaceae",
    genus: "Dracaena",
    species: "sanderiana",
    tags: ["palm", "lucky", "gift", "beginner", "low-light"],
    baseTraits: { rarity: 10, demand: 60, careDifficulty: 10, propagationSpeed: 50 },
    baseFMV: 12,
  },

  // FIGS
  {
    id: "fiddle-leaf-fig",
    name: "Fiddle Leaf Fig",
    image: "/plants/007-fiddle leaf fig.svg",
    family: "Fig",
    genus: "Ficus",
    species: "lyrata",
    tags: ["fig", "statement", "large", "trendy", "dramatic"],
    baseTraits: { rarity: 40, demand: 85, careDifficulty: 55, propagationSpeed: 25 },
    baseFMV: 55,
  },

  // MONEY PLANTS
  {
    id: "money-tree",
    name: "Money Tree",
    image: "/plants/008-guiana chestnut.svg",
    family: "Mallow",
    genus: "Pachira",
    species: "aquatica",
    tags: ["tree", "braided", "lucky", "gift", "statement"],
    baseTraits: { rarity: 30, demand: 75, careDifficulty: 30, propagationSpeed: 40 },
    baseFMV: 32,
  },
  {
    id: "pilea",
    name: "Chinese Money Plant",
    image: "/plants/009-chinese money plant.svg",
    family: "Nettle",
    genus: "Pilea",
    species: "peperomioides",
    tags: ["compact", "round-leaves", "trendy", "propagates-easy", "shareable"],
    baseTraits: { rarity: 25, demand: 80, careDifficulty: 25, propagationSpeed: 75 },
    baseFMV: 18,
  },

  // SUCCULENTS & CACTI
  {
    id: "aloe-vera",
    name: "Aloe Vera",
    image: "/plants/018-aloe vera.svg",
    family: "Asphodelaceae",
    genus: "Aloe",
    species: "vera",
    tags: ["succulent", "medicinal", "beginner", "easy-care", "healing"],
    baseTraits: { rarity: 10, demand: 60, careDifficulty: 10, propagationSpeed: 70 },
    baseFMV: 10,
  },
  {
    id: "jade",
    name: "Jade Plant",
    image: "/plants/026-jade.svg",
    family: "Crassulaceae",
    genus: "Crassula",
    species: "ovata",
    tags: ["succulent", "lucky", "beginner", "easy-care", "compact"],
    baseTraits: { rarity: 15, demand: 65, careDifficulty: 15, propagationSpeed: 65 },
    baseFMV: 15,
  },
  {
    id: "kalanchoe",
    name: "Kalanchoe",
    image: "/plants/027-kalanchoe.svg",
    family: "Crassulaceae",
    genus: "Kalanchoe",
    species: "blossfeldiana",
    tags: ["succulent", "flowering", "colorful", "beginner", "compact"],
    baseTraits: { rarity: 20, demand: 60, careDifficulty: 20, propagationSpeed: 60 },
    baseFMV: 18,
  },
  {
    id: "crown-of-thorns",
    name: "Crown of Thorns",
    image: "/plants/033-crown of thorns.svg",
    family: "Euphorbiaceae",
    genus: "Euphorbia",
    species: "milii",
    tags: ["succulent", "flowering", "drought-tolerant", "beginner"],
    baseTraits: { rarity: 25, demand: 55, careDifficulty: 20, propagationSpeed: 50 },
    baseFMV: 20,
  },
  {
    id: "succulent",
    name: "Succulent",
    image: "/plants/038-Succulent.svg",
    family: "Various",
    genus: "Various",
    species: "spp",
    tags: ["succulent", "beginner", "easy-care", "drought-tolerant", "compact"],
    baseTraits: { rarity: 5, demand: 50, careDifficulty: 5, propagationSpeed: 80 },
    baseFMV: 8,
  },
  {
    id: "cactus",
    name: "Cactus",
    image: "/plants/041-cactus.svg",
    family: "Cactaceae",
    genus: "Various",
    species: "spp",
    tags: ["cactus", "beginner", "easy-care", "drought-tolerant", "desert"],
    baseTraits: { rarity: 10, demand: 55, careDifficulty: 10, propagationSpeed: 60 },
    baseFMV: 12,
  },
  {
    id: "barrel-cactus",
    name: "Barrel Cactus",
    image: "/plants/045-cactus.svg",
    family: "Cactaceae",
    genus: "Echinocactus",
    species: "grusonii",
    tags: ["cactus", "round", "desert", "architectural", "beginner"],
    baseTraits: { rarity: 20, demand: 60, careDifficulty: 15, propagationSpeed: 40 },
    baseFMV: 18,
  },
  {
    id: "lithops",
    name: "Living Stones",
    image: "/plants/042-lithops.svg",
    family: "Aizoaceae",
    genus: "Lithops",
    species: "spp",
    tags: ["succulent", "unusual", "collector", "desert", "slow-growing"],
    baseTraits: { rarity: 60, demand: 70, careDifficulty: 70, propagationSpeed: 20 },
    baseFMV: 50,
  },
  {
    id: "christmas-cactus",
    name: "Christmas Cactus",
    image: "/plants/034-christmas.svg",
    family: "Cactaceae",
    genus: "Schlumbergera",
    species: "bridgesii",
    tags: ["cactus", "flowering", "holiday", "beginner", "colorful"],
    baseTraits: { rarity: 20, demand: 65, careDifficulty: 25, propagationSpeed: 55 },
    baseFMV: 22,
  },

  // SNAKE PLANTS / SANSEVIERIA
  {
    id: "snake-plant",
    name: "Snake Plant",
    image: "/plants/035-snake plant.svg",
    family: "Asparagaceae",
    genus: "Sansevieria",
    species: "trifasciata",
    tags: ["succulent", "air-purifying", "beginner", "easy-care", "low-light"],
    baseTraits: { rarity: 15, demand: 75, careDifficulty: 10, propagationSpeed: 50 },
    baseFMV: 18,
  },
  {
    id: "zanzibar-gem",
    name: "ZZ Plant",
    image: "/plants/047-zanzibar gem.svg",
    family: "Araceae",
    genus: "Zamioculcas",
    species: "zamiifolia",
    tags: ["aroid", "air-purifying", "beginner", "easy-care", "low-light", "indestructible"],
    baseTraits: { rarity: 20, demand: 80, careDifficulty: 10, propagationSpeed: 30 },
    baseFMV: 25,
  },
  {
    id: "sansevieria",
    name: "Sansevieria",
    image: "/plants/048-sansevieria.svg",
    family: "Asparagaceae",
    genus: "Sansevieria",
    species: "cylindrica",
    tags: ["succulent", "architectural", "beginner", "easy-care", "modern"],
    baseTraits: { rarity: 25, demand: 70, careDifficulty: 15, propagationSpeed: 45 },
    baseFMV: 22,
  },

  // OTHER POPULAR PLANTS
  {
    id: "yucca",
    name: "Yucca",
    image: "/plants/011-yucca.svg",
    family: "Asparagaceae",
    genus: "Yucca",
    species: "elephantipes",
    tags: ["tree", "architectural", "statement", "drought-tolerant", "beginner"],
    baseTraits: { rarity: 25, demand: 60, careDifficulty: 20, propagationSpeed: 30 },
    baseFMV: 28,
  },
  {
    id: "african-violets",
    name: "African Violets",
    image: "/plants/012-african violets.svg",
    family: "Gesneriaceae",
    genus: "Saintpaulia",
    species: "ionantha",
    tags: ["flowering", "colorful", "compact", "indoor", "delicate"],
    baseTraits: { rarity: 30, demand: 65, careDifficulty: 40, propagationSpeed: 60 },
    baseFMV: 25,
  },
  {
    id: "peperomia",
    name: "Peperomia",
    image: "/plants/013-peperomia.svg",
    family: "Piperaceae",
    genus: "Peperomia",
    species: "obtusifolia",
    tags: ["compact", "beginner", "easy-care", "versatile", "trailing"],
    baseTraits: { rarity: 20, demand: 65, careDifficulty: 20, propagationSpeed: 65 },
    baseFMV: 18,
  },
  {
    id: "air-plant",
    name: "Air Plant",
    image: "/plants/014-air plant.svg",
    family: "Bromeliaceae",
    genus: "Tillandsia",
    species: "spp",
    tags: ["epiphytic", "unusual", "no-soil", "collector", "modern"],
    baseTraits: { rarity: 35, demand: 70, careDifficulty: 45, propagationSpeed: 30 },
    baseFMV: 30,
  },
  {
    id: "spider-plant",
    name: "Spider Plant",
    image: "/plants/015-spider plant.svg",
    family: "Asparagaceae",
    genus: "Chlorophytum",
    species: "comosum",
    tags: ["trailing", "air-purifying", "beginner", "easy-care", "propagates-easy"],
    baseTraits: { rarity: 10, demand: 70, careDifficulty: 10, propagationSpeed: 90 },
    baseFMV: 12,
  },
  {
    id: "english-ivy",
    name: "English Ivy",
    image: "/plants/019-english ivy.svg",
    family: "Araliaceae",
    genus: "Hedera",
    species: "helix",
    tags: ["trailing", "vining", "beginner", "easy-care", "classic"],
    baseTraits: { rarity: 15, demand: 60, careDifficulty: 15, propagationSpeed: 75 },
    baseFMV: 15,
  },
  {
    id: "dragon-tree",
    name: "Dragon Tree",
    image: "/plants/020-dragon tree.svg",
    family: "Asparagaceae",
    genus: "Dracaena",
    species: "marginata",
    tags: ["tree", "architectural", "air-purifying", "beginner", "statement"],
    baseTraits: { rarity: 20, demand: 70, careDifficulty: 20, propagationSpeed: 35 },
    baseFMV: 25,
  },
  {
    id: "croton",
    name: "Croton",
    image: "/plants/023-croton.svg",
    family: "Euphorbiaceae",
    genus: "Codiaeum",
    species: "variegatum",
    tags: ["colorful", "tropical", "patterned", "statement", "bright-light"],
    baseTraits: { rarity: 30, demand: 65, careDifficulty: 40, propagationSpeed: 40 },
    baseFMV: 28,
  },
  {
    id: "bromeliad",
    name: "Bromeliad",
    image: "/plants/025-bromeliad.svg",
    family: "Bromeliaceae",
    genus: "Guzmania",
    species: "lingulata",
    tags: ["tropical", "flowering", "colorful", "epiphytic", "statement"],
    baseTraits: { rarity: 35, demand: 70, careDifficulty: 35, propagationSpeed: 25 },
    baseFMV: 32,
  },
  {
    id: "begonia",
    name: "Begonia",
    image: "/plants/032-begonia.svg",
    family: "Begoniaceae",
    genus: "Begonia",
    species: "rex",
    tags: ["flowering", "colorful", "patterned", "collector", "delicate"],
    baseTraits: { rarity: 40, demand: 75, careDifficulty: 50, propagationSpeed: 50 },
    baseFMV: 35,
  },
  {
    id: "schefflera",
    name: "Umbrella Tree",
    image: "/plants/036-scefflera.svg",
    family: "Araliaceae",
    genus: "Schefflera",
    species: "actinophylla",
    tags: ["tree", "statement", "large", "beginner", "tropical"],
    baseTraits: { rarity: 25, demand: 65, careDifficulty: 25, propagationSpeed: 40 },
    baseFMV: 28,
  },
  {
    id: "cast-iron-plant",
    name: "Cast Iron Plant",
    image: "/plants/037-cast iron plant.svg",
    family: "Asparagaceae",
    genus: "Aspidistra",
    species: "elatior",
    tags: ["indestructible", "low-light", "beginner", "easy-care", "classic"],
    baseTraits: { rarity: 20, demand: 60, careDifficulty: 10, propagationSpeed: 25 },
    baseFMV: 22,
  },
  {
    id: "banana-plant",
    name: "Banana Plant",
    image: "/plants/039-banana plant.svg",
    family: "Musaceae",
    genus: "Musa",
    species: "acuminata",
    tags: ["tropical", "large", "statement", "dramatic", "fast-growing"],
    baseTraits: { rarity: 45, demand: 75, careDifficulty: 50, propagationSpeed: 70 },
    baseFMV: 40,
  },
  {
    id: "carnivorous-plant",
    name: "Carnivorous Plant",
    image: "/plants/040-carnivorous plant.svg",
    family: "Droseraceae",
    genus: "Dionaea",
    species: "muscipula",
    tags: ["unusual", "collector", "specialized", "novelty", "rare"],
    baseTraits: { rarity: 65, demand: 80, careDifficulty: 75, propagationSpeed: 20 },
    baseFMV: 60,
  },
  {
    id: "hoya-carnosa",
    name: "Hoya",
    image: "/plants/044-hoya carnosa.svg",
    family: "Apocynaceae",
    genus: "Hoya",
    species: "carnosa",
    tags: ["trailing", "flowering", "waxy", "collector", "fragrant"],
    baseTraits: { rarity: 40, demand: 75, careDifficulty: 35, propagationSpeed: 50 },
    baseFMV: 35,
  },
  {
    id: "phalaenopsis-orchid",
    name: "Phalaenopsis Orchid",
    image: "/plants/030-phalaenopsis orchid.svg",
    family: "Orchidaceae",
    genus: "Phalaenopsis",
    species: "spp",
    tags: ["orchid", "flowering", "elegant", "collector", "delicate"],
    baseTraits: { rarity: 50, demand: 85, careDifficulty: 60, propagationSpeed: 25 },
    baseFMV: 50,
  },
  {
    id: "baby-tears",
    name: "Baby's Tears",
    image: "/plants/049-baby tears.svg",
    family: "Urticaceae",
    genus: "Soleirolia",
    species: "soleirolii",
    tags: ["trailing", "compact", "delicate", "moisture-loving", "ground-cover"],
    baseTraits: { rarity: 30, demand: 60, careDifficulty: 40, propagationSpeed: 80 },
    baseFMV: 22,
  },
  {
    id: "aglaonema",
    name: "Aglaonema",
    image: "/plants/050-aglaonema.svg",
    family: "Araceae",
    genus: "Aglaonema",
    species: "spp",
    tags: ["aroid", "low-light", "beginner", "patterned", "easy-care"],
    baseTraits: { rarity: 25, demand: 70, careDifficulty: 20, propagationSpeed: 45 },
    baseFMV: 25,
  },
]

export const CUSTOMERS: Customer[] = [
  {
    id: "collector-clara",
    name: "Clara Chen",
    avatar: "🧐",
    archetype: "Collector",
    preferredTags: ["rare", "collector", "velvet"],
    avoidTags: ["beginner", "common"],
    traitMinimums: { rarity: 50 },
    budgetMin: 60,
    budgetMax: 200,
    generosity: 1.2,
  },
  {
    id: "beginner-ben",
    name: "Ben Parker",
    avatar: "😊",
    archetype: "Beginner",
    preferredTags: ["easy-care", "beginner", "low-light"],
    avoidTags: ["rare", "fragile"],
    traitMinimums: { careDifficulty: 0 },
    budgetMin: 5,
    budgetMax: 30,
    generosity: 1.0,
  },
  {
    id: "designer-diana",
    name: "Diana Ross",
    avatar: "✨",
    archetype: "Interior Designer",
    preferredTags: ["statement", "large", "trailing", "unusual"],
    avoidTags: [],
    traitMinimums: { demand: 50 },
    budgetMin: 30,
    budgetMax: 150,
    generosity: 1.15,
  },
  {
    id: "botanist-boris",
    name: "Dr. Boris Ivy",
    avatar: "🔬",
    archetype: "Botanist",
    preferredTags: ["rare", "fenestrated", "crawling"],
    avoidTags: [],
    traitMinimums: { rarity: 40 },
    budgetMin: 40,
    budgetMax: 180,
    generosity: 1.1,
  },
  {
    id: "gift-grace",
    name: "Grace Liu",
    avatar: "🎁",
    archetype: "Gift Shopper",
    preferredTags: ["heart-shaped", "colorful", "compact", "popular"],
    avoidTags: ["fragile", "humidity-loving"],
    traitMinimums: {},
    budgetMin: 15,
    budgetMax: 50,
    generosity: 0.95,
  },
  {
    id: "collector-marcus",
    name: "Marcus Webb",
    avatar: "🌿",
    archetype: "Collector",
    preferredTags: ["tropical", "velvet", "rare"],
    avoidTags: [],
    traitMinimums: { rarity: 60, demand: 60 },
    budgetMin: 80,
    budgetMax: 250,
    generosity: 1.3,
  },
  {
    id: "beginner-sarah",
    name: "Sarah Mills",
    avatar: "🌱",
    archetype: "Beginner",
    preferredTags: ["succulent", "easy-care", "compact"],
    avoidTags: ["rare", "humidity-loving"],
    traitMinimums: {},
    budgetMin: 8,
    budgetMax: 25,
    generosity: 0.9,
  },
  {
    id: "designer-alex",
    name: "Alex Morgan",
    avatar: "🏠",
    archetype: "Interior Designer",
    preferredTags: ["hanging", "trailing", "lush"],
    avoidTags: ["compact"],
    traitMinimums: { demand: 40 },
    budgetMin: 20,
    budgetMax: 80,
    generosity: 1.05,
  },
  {
    id: "botanist-emma",
    name: "Prof. Emma Bloom",
    avatar: "📚",
    archetype: "Botanist",
    preferredTags: ["unusual", "fern", "mounted"],
    avoidTags: [],
    traitMinimums: { rarity: 30 },
    budgetMin: 35,
    budgetMax: 120,
    generosity: 1.1,
  },
  {
    id: "gift-tom",
    name: "Tom Baker",
    avatar: "💐",
    archetype: "Gift Shopper",
    preferredTags: ["flowering", "rosette", "iconic"],
    avoidTags: ["slow-growing"],
    traitMinimums: {},
    budgetMin: 10,
    budgetMax: 40,
    generosity: 1.0,
  },
]

export const SELLERS: Seller[] = [
  {
    id: "honest-helen",
    name: "Honest Helen",
    persona: "Honest Hobbyist",
    honesty: 0.95,
    pricingStyle: "at",
    specialties: ["succulent", "easy-care"],
  },
  {
    id: "shady-steve",
    name: "Shady Steve",
    persona: "Shady Flipper",
    honesty: 0.3,
    pricingStyle: "above",
    specialties: ["rare", "tropical"],
  },
  {
    id: "estate-ellen",
    name: "Estate Ellen",
    persona: "Estate Sale",
    honesty: 0.6,
    pricingStyle: "below",
    specialties: ["fern", "flowering"],
  },
  {
    id: "greenhouse-gary",
    name: "Greenhouse Gary",
    persona: "Greenhouse Pro",
    honesty: 0.85,
    pricingStyle: "at",
    specialties: ["tropical", "rare", "collector"],
  },
  {
    id: "rescue-rosa",
    name: "Rescue Rosa",
    persona: "Plant Rescue",
    honesty: 0.75,
    pricingStyle: "below",
    specialties: ["easy-care", "beginner"],
  },
  {
    id: "mystery-max",
    name: "Mystery Max",
    persona: "Mystery Trader",
    honesty: 0.45,
    pricingStyle: "above",
    specialties: ["rare", "unusual", "collector"],
  },
]

export const VARIANTS = ["Variegated", "Albo", "Aurea", "Pink Princess", "Monstrose", "Crested"]
