import type { PlantSeed, Customer, Seller } from "./types"

export const PLANT_SEEDS: PlantSeed[] = [
  // FERN FAMILY - Feathery, delicate fronds
  {
    id: "asparagus-fern",
    name: "Asparagus Fern",
    image: "/plants/asparagus-fern.svg",
    family: "Fern",
    genus: "Asparagus",
    species: "setaceus",
    tags: ["fern", "feathery", "trailing", "delicate"],
    baseTraits: { rarity: 25, demand: 55, careDifficulty: 35, propagationSpeed: 60 },
    baseFMV: 15,
  },

  // AROID FAMILY - Bold tropical leaves
  {
    id: "chinese-evergreen",
    name: "Chinese Evergreen",
    image: "/plants/chinese-evergreen.svg",
    family: "Aroid",
    genus: "Aglaonema",
    species: "commutatum",
    tags: ["aroid", "low-light", "beginner", "patterned"],
    baseTraits: { rarity: 20, demand: 65, careDifficulty: 15, propagationSpeed: 50 },
    baseFMV: 18,
  },
  {
    id: "monstera",
    name: "Monstera",
    image: "/plants/monstera.svg",
    family: "Aroid",
    genus: "Monstera",
    species: "deliciosa",
    tags: ["aroid", "tropical", "fenestrated", "statement", "popular"],
    baseTraits: { rarity: 30, demand: 90, careDifficulty: 25, propagationSpeed: 45 },
    baseFMV: 35,
  },
  {
    id: "pothos",
    name: "Pothos",
    image: "/plants/pothos.svg",
    family: "Aroid",
    genus: "Epipremnum",
    species: "aureum",
    tags: ["aroid", "trailing", "beginner", "easy-care", "versatile"],
    baseTraits: { rarity: 10, demand: 70, careDifficulty: 10, propagationSpeed: 85 },
    baseFMV: 8,
  },
  {
    id: "alocasia",
    name: "Alocasia",
    image: "/plants/alocasia.svg",
    family: "Aroid",
    genus: "Alocasia",
    species: "amazonica",
    tags: ["aroid", "tropical", "dramatic", "collector", "bold"],
    baseTraits: { rarity: 55, demand: 75, careDifficulty: 60, propagationSpeed: 30 },
    baseFMV: 45,
  },

  // PRAYER PLANT FAMILY - Folding leaves, patterns
  {
    id: "prayer-plant",
    name: "Prayer Plant",
    image: "/plants/prayer-plant.svg",
    family: "Marantaceae",
    genus: "Maranta",
    species: "leuconeura",
    tags: ["prayer-plant", "patterned", "colorful", "movement"],
    baseTraits: { rarity: 35, demand: 70, careDifficulty: 45, propagationSpeed: 55 },
    baseFMV: 22,
  },

  // PALM FAMILY - Tropical fronds
  {
    id: "parlor-palm",
    name: "Parlor Palm",
    image: "/plants/parlor-palm.svg",
    family: "Palm",
    genus: "Chamaedorea",
    species: "elegans",
    tags: ["palm", "low-light", "elegant", "classic", "beginner"],
    baseTraits: { rarity: 15, demand: 60, careDifficulty: 20, propagationSpeed: 35 },
    baseFMV: 20,
  },

  // FIG FAMILY - Bold statement plants
  {
    id: "fiddle-leaf-fig",
    name: "Fiddle Leaf Fig",
    image: "/plants/fiddle-leaf-fig.svg",
    family: "Fig",
    genus: "Ficus",
    species: "lyrata",
    tags: ["fig", "statement", "large", "trendy", "dramatic"],
    baseTraits: { rarity: 40, demand: 85, careDifficulty: 55, propagationSpeed: 25 },
    baseFMV: 55,
  },

  // MONEY PLANT FAMILY - Prosperity & luck
  {
    id: "money-tree",
    name: "Money Tree",
    image: "/plants/money-tree.svg",
    family: "Mallow",
    genus: "Pachira",
    species: "aquatica",
    tags: ["tree", "braided", "lucky", "gift", "statement"],
    baseTraits: { rarity: 30, demand: 75, careDifficulty: 30, propagationSpeed: 40 },
    baseFMV: 32,
  },
  {
    id: "pilea",
    name: "Pilea",
    image: "/plants/pilea.svg",
    family: "Nettle",
    genus: "Pilea",
    species: "peperomioides",
    tags: ["compact", "round-leaves", "trendy", "propagates-easy", "shareable"],
    baseTraits: { rarity: 25, demand: 80, careDifficulty: 25, propagationSpeed: 75 },
    baseFMV: 18,
  },
]

export const CUSTOMERS: Customer[] = [
  {
    id: "collector-clara",
    name: "Clara Chen",
    avatar: "🧐",
    archetype: "Collector",
    preferredTags: ["rare", "collector", "velvet"],
    avoidTags: ["beginner", "common"],
    traitMinimums: { rarity: 50 },
    budgetMin: 60,
    budgetMax: 200,
    generosity: 1.2,
  },
  {
    id: "beginner-ben",
    name: "Ben Parker",
    avatar: "😊",
    archetype: "Beginner",
    preferredTags: ["easy-care", "beginner", "low-light"],
    avoidTags: ["rare", "fragile"],
    traitMinimums: { careDifficulty: 0 },
    budgetMin: 5,
    budgetMax: 30,
    generosity: 1.0,
  },
  {
    id: "designer-diana",
    name: "Diana Ross",
    avatar: "✨",
    archetype: "Interior Designer",
    preferredTags: ["statement", "large", "trailing", "unusual"],
    avoidTags: [],
    traitMinimums: { demand: 50 },
    budgetMin: 30,
    budgetMax: 150,
    generosity: 1.15,
  },
  {
    id: "botanist-boris",
    name: "Dr. Boris Ivy",
    avatar: "🔬",
    archetype: "Botanist",
    preferredTags: ["rare", "fenestrated", "crawling"],
    avoidTags: [],
    traitMinimums: { rarity: 40 },
    budgetMin: 40,
    budgetMax: 180,
    generosity: 1.1,
  },
  {
    id: "gift-grace",
    name: "Grace Liu",
    avatar: "🎁",
    archetype: "Gift Shopper",
    preferredTags: ["heart-shaped", "colorful", "compact", "popular"],
    avoidTags: ["fragile", "humidity-loving"],
    traitMinimums: {},
    budgetMin: 15,
    budgetMax: 50,
    generosity: 0.95,
  },
  {
    id: "collector-marcus",
    name: "Marcus Webb",
    avatar: "🌿",
    archetype: "Collector",
    preferredTags: ["tropical", "velvet", "rare"],
    avoidTags: [],
    traitMinimums: { rarity: 60, demand: 60 },
    budgetMin: 80,
    budgetMax: 250,
    generosity: 1.3,
  },
  {
    id: "beginner-sarah",
    name: "Sarah Mills",
    avatar: "🌱",
    archetype: "Beginner",
    preferredTags: ["succulent", "easy-care", "compact"],
    avoidTags: ["rare", "humidity-loving"],
    traitMinimums: {},
    budgetMin: 8,
    budgetMax: 25,
    generosity: 0.9,
  },
  {
    id: "designer-alex",
    name: "Alex Morgan",
    avatar: "🏠",
    archetype: "Interior Designer",
    preferredTags: ["hanging", "trailing", "lush"],
    avoidTags: ["compact"],
    traitMinimums: { demand: 40 },
    budgetMin: 20,
    budgetMax: 80,
    generosity: 1.05,
  },
  {
    id: "botanist-emma",
    name: "Prof. Emma Bloom",
    avatar: "📚",
    archetype: "Botanist",
    preferredTags: ["unusual", "fern", "mounted"],
    avoidTags: [],
    traitMinimums: { rarity: 30 },
    budgetMin: 35,
    budgetMax: 120,
    generosity: 1.1,
  },
  {
    id: "gift-tom",
    name: "Tom Baker",
    avatar: "💐",
    archetype: "Gift Shopper",
    preferredTags: ["flowering", "rosette", "iconic"],
    avoidTags: ["slow-growing"],
    traitMinimums: {},
    budgetMin: 10,
    budgetMax: 40,
    generosity: 1.0,
  },
]

export const SELLERS: Seller[] = [
  {
    id: "honest-helen",
    name: "Honest Helen",
    persona: "Honest Hobbyist",
    honesty: 0.95,
    pricingStyle: "at",
    specialties: ["succulent", "easy-care"],
  },
  {
    id: "shady-steve",
    name: "Shady Steve",
    persona: "Shady Flipper",
    honesty: 0.3,
    pricingStyle: "above",
    specialties: ["rare", "tropical"],
  },
  {
    id: "estate-ellen",
    name: "Estate Ellen",
    persona: "Estate Sale",
    honesty: 0.6,
    pricingStyle: "below",
    specialties: ["fern", "flowering"],
  },
  {
    id: "greenhouse-gary",
    name: "Greenhouse Gary",
    persona: "Greenhouse Pro",
    honesty: 0.85,
    pricingStyle: "at",
    specialties: ["tropical", "rare", "collector"],
  },
  {
    id: "rescue-rosa",
    name: "Rescue Rosa",
    persona: "Plant Rescue",
    honesty: 0.75,
    pricingStyle: "below",
    specialties: ["easy-care", "beginner"],
  },
  {
    id: "mystery-max",
    name: "Mystery Max",
    persona: "Mystery Trader",
    honesty: 0.45,
    pricingStyle: "above",
    specialties: ["rare", "unusual", "collector"],
  },
]

export const VARIANTS = ["Variegated", "Albo", "Aurea", "Pink Princess", "Monstrose", "Crested"]
